services:
  mypassencoder_encoder:
        class: UC\UsersBundle\Service\MyPassEncoder
#    uc_users.example:
#        class: UC\UsersBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
