<?php

namespace EM\EstudiantesMatriculasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatriculasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatriculasRepository extends EntityRepository
{
}
